### ISSUE TITLE
How to Compile the app.

### ISSUE THREAD

**Issue by osmaniastudent** [chaquo/chaquopy-matplotlib#10]
Please explain me How to compile the app using Command line in windows.
If I run Gradlew empty process is done with build succesful  and no APK generation.
Please help Thank you.

**Comment by mhsmith** [comment]
On Windows the command should be something like `gradlew.bat assembleDebug`. Make sure your working directory is the root of the repository.

If you're having trouble with the command line tools, I suggest you open the app in Android Studio instead, as documentation for that is much easier to find.
