### ISSUE TITLE
Could  chaquopy be used for desktop application?

### ISSUE THREAD

**Issue by Harrisonust** [chaquo/chaquopy-matplotlib#3]

**Comment by Harrisonust** [comment]
I am tring to integrade chaquopy with desktop by Intellij Idea, but failed. I am not sure if this library could be used for other application such as JavaFx or TornadoFx.

**Comment by mhsmith** [comment]
Chaquopy currently only supports Android. For integrating Python and Java components on desktop platforms, have look at the following projects:
* Pyjnius
* Jython
* Jpy
