### ISSUE TITLE
Failed to install contourpy>=1.0.1

### ISSUE THREAD

**Issue by Vivekpkd** [chaquo/chaquopy-matplotlib#8]
While building gradle for matplotlib below error is coming .

**ERROR: Failed to install contourpy>=1.0.1 from https://pypi.tuna.tsinghua.edu.cn/packages/b1/7d/087ee4295e7580d3f7eb8a8a4e0ec8c7847e60f34135248ccf831cf5bbfc/contourpy-1.1.1.tar.gz#sha256=96ba37c2e24b7212a77da85004c38e7c4d155d3e72a45eeaf22c1f03f607e8ab (from matplotlib).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.**
    ERROR: Command errored out with exit status 1:
    Complete output (35 lines):
    Traceback (most recent call last):
      File "C:\Users\vivek\AndroidStudioProjects\Py\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:

Let me know you need more info.

**Comment by mhsmith** [comment]
I see you've modified the app to add the tsinghua repository. Did you modify it in any other ways?

**Comment by mhsmith** [comment]
If you still need help, please provide the requested information, and I'll reopen the issue.
